name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "37 7 * * 1"
env:
  CARGO_TERM_COLOR: always

jobs:
  timeout-minutes: 20
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable
    - name: Install nextest
      run: cargo install cargo-nextest
    - name: Run tests
      run: cargo +stable nextest run --workspace
    - name: Miri
      run: rustup component add --toolchain nightly miri && cargo +nightly miri test miri
    - name: Docs
      run: cargo +stable test --doc




