name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "37 7 * * 1"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable && rustup toolchain install 1.87
    - name: Install nextest
      run: cargo install --locked cargo-nextest
    - name: Run bench
      run: cd db_bench && cargo +stable run --release
    - name: Build examples
      run: cargo build --examples
    - name: Run tests
      run: cargo +stable nextest run --workspace
    - name: Run tests -no-default-features
      run: cargo +stable nextest run --no-default-features --workspace
    - name: Run tests all-features
      run: cargo +stable nextest run --all-features --workspace
    - name: Docs
      run: cargo +stable test --doc
    - name: Build (1.87)
      run: cargo +1.87 build --workspace --all-targets --all-features




